<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mips"
    nsURI="http://www.unisb.de/prog/mips/asm/Mips" nsPrefix="mips">
  <eClassifiers xsi:type="ecore:EClass" name="Asm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elem" upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextSegment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//TextItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Label" eType="#//Label"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opcode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="form" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RForm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rt" eType="#//Reg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rs" eType="#//Reg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rd" eType="#//Reg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shamt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IArithForm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rt" eType="#//Reg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rs" eType="#//Reg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IExpForm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rt" eType="#//Reg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rs" eType="#//Reg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILabelForm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reg" eType="#//Reg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//Label"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IBr2Form">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rt" eType="#//Reg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rs" eType="#//Reg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//Label"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BExpForm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BLabelForm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//Label"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecialInsn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="insn" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadConstant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rt" eType="#//Reg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadAddress">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rt" eType="#//Reg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//Label"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reg">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="num" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSegment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//DataItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//Label"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" eType="#//DataDecl"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Align">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="align" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Space">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bytes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Word">
    <eStructuralFeatures xsi:type="ecore:EReference" name="val" eType="#//IntList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Half">
    <eStructuralFeatures xsi:type="ecore:EReference" name="val" eType="#//IntList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Byte">
    <eStructuralFeatures xsi:type="ecore:EReference" name="val" eType="#//IntList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Str">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntList">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vals" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
