/*
 * generated by Xtext
 */
package de.unisb.prog.mips.parser;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MipsRuntimeModule extends de.unisb.prog.mips.parser.AbstractMipsRuntimeModule {

}
