/*
 * generated by Xtext
 */
package de.unisb.prog.mips.parser.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MipsUiModule extends de.unisb.prog.mips.parser.ui.AbstractMipsUiModule {
	public MipsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
