/*
* generated by Xtext
*/
package de.unisb.prog.mips.asm.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MipsAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/unisb/prog/mips/asm/parser/antlr/internal/InternalMips.tokens");
	}
}
