/*
* generated by Xtext
*/
package de.unisb.prog.mips.parser.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class MipsTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
